# @package _global_
data:
  train_path: data/an4_train_manifest.json
  val_path: data/an4_val_manifest.json
  batch_size: 8
  num_workers: 8
trainer:
  max_epochs: 70
  accelerator: 'auto'
  devices: 1
  precision: 16
  gradient_clip_val: 400  # Norm cutoff to prevent explosion of gradients
  strategy: ddp
  enable_checkpointing: True
checkpoint:
  save_top_k: 1
  monitor: "wer"
  verbose: True